name: BBC Weather Scraper

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:         # allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python collect_snapshots.py

      - name: Commit and push data
        run: |
          git config --global user.name "mrtwolf7"
          git config --global user.email "lupo.tiziano94@gmail.com"
          git add data/
          git commit -m "Update weather data" || echo "No changes"
          git push